[package]
name = "renewal"
version = "0.0.1"
edition = "2024"

[dependencies]
rand = "0.9.2"
rand_distr = "0.5.1"
nalgebra = "0.33.2"
serde = { version = "1.0.228", features = ["derive"] }
mrp = { path = "../../mrp-rs" }
