input = "./renewal/parameters.json"

[model]
spec = "renewal"
version = "0.0.1"

[runtime]
env = "uv"
command = "renewal"

[runtime.profile.rust]
command = "cargo"
args = ["run", "--manifest-path", "examples/renewal-rs/Cargo.toml"]

[output]
spec = "filesystem"
dir = "./output/renewal/"
