[model]
spec = "renewal"
version = "0.0.1"

[runtime]
env = "uv"
command = "renewal"

[output]
spec = "filesystem"
dir = "./output/renewal/"

[input]
r0 = 2.0
population_size = 100000
generation_interval_pmf = [0.0, 0.0, 0.25, 0.5, 0.25]
symptom_onset_pmf = [1.0]
initial_infections = [1]
sim_length = 200
