[runtime]
spec = "process"
command = "cargo"
args = ["run", "--manifest-path", "examples/renewal-rs/Cargo.toml"]

[output]
spec = "filesystem"
dir = "./output/renewal-rs/"

[input]
r0 = 2.0
population_size = 100000
generation_interval_pmf = [0.0, 0.0, 0.25, 0.5, 0.25]
symptom_onset_pmf = [1.0]
initial_infections = [1]
sim_length = 200
